name = "Kimi K2.5"
family = "kimi"
attachment = true
reasoning = true
tool_call = true
temperature = true
knowledge = "2025-01"
release_date = "2026-01-26"
last_updated = "2026-06-27"
open_weights = true

interleaved = true

[cost]
input = 0.6
output = 3
cache_read = 0.09999999999999999

[limit]
context = 262_114
output = 262_114

[modalities]
input = ["text", "image"]
output = ["text"]
