name = "Nemotron 3 Nano 30B A3B"
family = "nemotron"
attachment = false
reasoning = true
tool_call = false
temperature = true
knowledge = "2024-10"
release_date = "2025-12-15"
last_updated = "2026-06-27"
open_weights = false

[cost]
input = 0.049999999999999996
output = 0.24

[limit]
context = 262_144
output = 262_144

[modalities]
input = ["text"]
output = ["text"]
