name = "Nvidia Nemotron Nano 9B V2"
family = "nemotron"
attachment = false
reasoning = true
tool_call = true
temperature = true
knowledge = "2024-10"
release_date = "2025-08-18"
last_updated = "2026-06-27"
open_weights = false

[cost]
input = 0.06
output = 0.22999999999999998

[limit]
context = 131_072
output = 131_072

[modalities]
input = ["text"]
output = ["text"]
