name = "DeepSeek V3 0324"
family = "deepseek"
attachment = false
reasoning = false
tool_call = true
temperature = true
knowledge = "2024-07"
release_date = "2024-12-26"
last_updated = "2026-06-27"
open_weights = false

[cost]
input = 0.27
output = 1.12
cache_read = 0.135

[limit]
context = 163_840
output = 163_840

[modalities]
input = ["text"]
output = ["text"]
