name = "Kimi K2 Instruct"
family = "kimi"
attachment = false
reasoning = false
tool_call = true
temperature = true
knowledge = "2024-10"
release_date = "2025-07-11"
last_updated = "2026-06-27"
open_weights = true
status = "deprecated"

[cost]
input = 0.5700000000000001
output = 2.3

[limit]
context = 131_072
output = 131_072

[modalities]
input = ["text"]
output = ["text"]
