name = "MiMo V2 Flash"
family = "mimo"
attachment = false
reasoning = true
tool_call = true
temperature = true
knowledge = "2024-10"
release_date = "2025-12-16"
last_updated = "2026-06-27"
open_weights = false

[cost]
input = 0.09999999999999999
output = 0.3
cache_read = 0.01

[limit]
context = 262_144
output = 32_000

[modalities]
input = ["text"]
output = ["text"]
