name = "Qwen3 235B A22B Thinking 2507"
family = "qwen"
attachment = true
reasoning = true
tool_call = true
temperature = true
knowledge = "2025-04"
release_date = "2025-09-23"
last_updated = "2026-06-27"
open_weights = false

[cost]
input = 0.39999999999999997
output = 4

[limit]
context = 131_072
output = 32_768

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]
