name = "Morph v3 Large"
family = "morph"
attachment = false
reasoning = false
tool_call = false
temperature = true
release_date = "2025-07-07"
last_updated = "2026-06-27"
open_weights = false

[cost]
input = 0.8999999999999999
output = 1.9

[limit]
context = 81_920
output = 16_384

[modalities]
input = ["text"]
output = ["text"]
