name = "Nova 2 Lite"
family = "nova"
attachment = true
reasoning = true
tool_call = false
temperature = true
knowledge = "2024-10"
release_date = "2025-12-02"
last_updated = "2026-06-27"
open_weights = false

[cost]
input = 0.3
output = 2.5
cache_read = 0.075

[limit]
context = 1_000_000
output = 1_000_000

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]
