name = "NVIDIA Nemotron 3 Super 120B A12B NVFP4"
family = "nemotron"
attachment = false
reasoning = false
tool_call = true
temperature = true
open_weights = true
knowledge = "2024-10"
release_date = "2025-01-20"
last_updated = "2025-01-20"

[cost]
input = 0.20
output = 0.80

[limit]
context = 260_000
output = 8_192

[modalities]
input = ["text"]
output = ["text"]
