name = "CoreThink (free)"
release_date = "2025-08-27"
last_updated = "2026-03-15"
attachment = false
reasoning = false
temperature = true
tool_call = true
open_weights = false

[cost]
input = 0
output = 0

[limit]
context = 78000
output = 8192

[modalities]
input = ["text"]
output = ["text"]
