name = "GLM-5"
family = "glm"
attachment = false
reasoning = true
tool_call = true
temperature = true
release_date = "2026-02-12"
last_updated = "2026-06-27"
open_weights = true

[cost]
input = 0.95
output = 3.15
cache_read = 0.19999999999999998

[limit]
context = 202_800
output = 131_100

[modalities]
input = ["text"]
output = ["text"]
