name = "Grok 4.1 Fast Non-Reasoning"
family = "grok"
attachment = false
reasoning = false
tool_call = true
temperature = true
knowledge = "2024-10"
release_date = "2025-11-19"
last_updated = "2026-06-27"
open_weights = false

[cost]
input = 0.19999999999999998
output = 0.5
cache_read = 0.049999999999999996

[limit]
context = 1_000_000
output = 1_000_000

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]
