name = "Sonar Reasoning Pro"
family = "sonar-reasoning"
attachment = false
reasoning = true
tool_call = false
temperature = true
knowledge = "2025-09"
release_date = "2025-02-19"
last_updated = "2026-06-27"
open_weights = false

[limit]
context = 127_000
output = 8_000

[modalities]
input = ["text"]
output = ["text"]
