name = "GPT OSS 20B"
family = "gpt-oss"
attachment = false
reasoning = true
tool_call = true
temperature = true
knowledge = "2024-10"
release_date = "2025-08-05"
last_updated = "2026-06-27"
open_weights = true

[cost]
input = 0.049999999999999996
output = 0.19999999999999998

[limit]
context = 131_072
output = 8_192

[modalities]
input = ["text"]
output = ["text"]
