name = "o3-deep-research"
family = "o"
attachment = true
reasoning = true
tool_call = true
temperature = true
knowledge = "2024-10"
release_date = "2025-06-26"
last_updated = "2026-06-27"
open_weights = false

[cost]
input = 10
output = 40
cache_read = 2.5

[limit]
context = 200_000
output = 100_000

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]
