name = "o3 Pro"
family = "o-pro"
attachment = true
reasoning = true
tool_call = true
temperature = true
knowledge = "2024-10"
release_date = "2025-06-10"
last_updated = "2026-06-27"
open_weights = false

[cost]
input = 20
output = 80

[limit]
context = 200_000
output = 100_000

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]
